artifact_location: file:///C:/Users/ayush/OneDrive/Documents/python/CrewAI/runs/mlflow/410434320674701082
creation_time: 1760729881503
experiment_id: '410434320674701082'
last_update_time: 1760729881503
lifecycle_stage: active
name: artifacts/yolo_detection
