artifact_location: file:///C:/Users/ayush/OneDrive/Documents/python/CrewAI/runs/mlflow/0
creation_time: 1760729881454
experiment_id: '0'
last_update_time: 1760729881454
lifecycle_stage: active
name: Default
