services:
  - type: web
    name: precision-agronomist
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ALERT_SENDER_EMAIL
        sync: false
      - key: ALERT_SENDER_PASSWORD
        sync: false
      - key: FARMER_EMAIL
        sync: false
