root_dir: artifacts

data_validation:
    root_dir: artifacts/data_validation
    STATUS_FILE: artifacts/data_validation/data_validation_status.txt
    train_data: data/train
    test_data: data/test
    val_data: data/valid

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_train_data: artifacts/data_transformation/train
  transformed_test_data: artifacts/data_transformation/test
  transformed_val_data: artifacts/data_transformation/val
  image_size: [224, 224]
  normalization_method: "imagenet"
  model_name: "ResNet50"
  color_mode: "rgb"
  data_format: "channels_last"

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.h5
  trained_model_yolo_path: artifacts/yolo_data
  trained_model_weights: artifacts/model_training/best_weights.weights.h5
  model_name: "ResNet50"
  image_size: [224, 224]
  num_classes: 11
  epochs: 5
  batch_size: 32
  learning_rate: 0.001
  early_stopping_patience: 10
  reduce_lr_patience: 5
  validation_split: 0.0
  use_class_weights: True
  freeze_base_layers: True
  fine_tune_from_layer: 100
  train_data: data/train
  test_data: data/test
  val_data: data/valid